### ISSUE TITLE
The GET method is not supported for this route. Supported methods: POST.

### ISSUE THREAD

**Issue by dgillier** [ralphjsmit/livewire-urls#5]
Hello,
I'm trying to use your component with Livewire and Laravel (9.40).

I added it in my Kernel web middleware section.

But I'm having most of the time an exception when I'm doing Url::previous();
`Symfony\ Component \ HttpKernel\ Exception \ MethodNotAllowedHttpException `
in public/index.php

I looked at the session data, and It looks it's coming from having a mix up with push between GET & POST  "http:localhost/members/push"
![Screenshot 2022-11-16 at 12 12 52](https://user-images.githubusercontent.com/37960204/202167022-8c094c89-526e-4288-b2ca-ccff86f86ce9.png)

Any suggestion ?
Thanks, Denis

**Comment by ralphjsmit** [comment]
Hey Denis, thanks for your bug report! Good catch and thanks for the session data.

I released a new version 1.1.3 with the fix for this. Can you confirm that this has been fixed for you? I'll close the issue for now, as I'll assume it has been fixed, but feel free to @mention me if there is an issue (you might need to clear your session).

**Comment by dgillier** [comment]
@ralphjsmit Thanks, solved (session need to be cleared)
